-- MySQL Script generated by MySQL Workbench
-- Mon Feb 24 14:11:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_prueba_tecnica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_prueba_tecnica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_prueba_tecnica` DEFAULT CHARACTER SET utf8 ;
USE `bd_prueba_tecnica` ;

-- -----------------------------------------------------
-- Table `bd_prueba_tecnica`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_prueba_tecnica`.`departamento` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_prueba_tecnica`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_prueba_tecnica`.`empleado` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `departamento_id` BIGINT NOT NULL,
  `numero_identificacion` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `direccion` TEXT NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_departamento_idx` (`departamento_id` ASC),
  CONSTRAINT `fk_departamento`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `bd_prueba_tecnica`.`departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
